### ISSUE TITLE
NPM deployment fails with Travis

### ISSUE THREAD

**Issue by bhufmann** [theia-ide/tsp-typescript-client#8]
I setup Travis but the deployment to NPM doesn't work. There seems to be some permission issue. 

I also tried it with my account but I don't have permission either.

**Comment by bhufmann** [comment]
@delislesim you deployed the initial versions and could you please provide access for me and Traviz CI?

**Comment by bhufmann** [comment]
I enabled Traviz today and it fails. 

@tahini @marcdumais-work do you know how to deploy this to NPM? Someone deployed it 2 month ago manually. I don't know who.

**Comment by delislesim** [comment]
@bhufmann I don't think I have access to it, I think @marcdumais-work was the one that set up the CI if I remember correctly. It look like your are using a different flow or version than the previous build, you are on build #1 with the new CI instead of #14. It seems that the npm token is not properly set-up for this "new" CI.

Error on Travis: `error No token found and can't prompt for login when running with --non-interactive.` probably the environment variable `NPM_AUTH_TOKEN` is not set in this environment

**Comment by bhufmann** [comment]
> @bhufmann I don't think I have access to it, I think @marcdumais-work was the one that set up the CI if I remember correctly. It look like your are using a different flow or version than the previous build, you are on build 1 with the new CI instead of 14. It seems that the npm token is not properly set-up for this "new" CI.
> 
> Error on Travis: `error No token found and can't prompt for login when running with --non-interactive.` probably the environment variable `NPM_AUTH_TOKEN` is not set in this environment

Thanks @delislesim for pointing this out. The token is not set. I'll check with @marcdumais-work for that.
